theme = "catppuccin_mocha"

[editor]
scrolloff = 2
bufferline = "multiple"
auto-save = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.soft-wrap]
enable = true

[keys.normal]
C-s = ":write" # Maps Ctrl-s to save
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
# space = { x = [":write:", "buffer-close"]}
esc = ["collapse_selection", "keep_primary_selection"]
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"

b = "record_macro"
B = "replay_macro"
q   = "move_prev_word_start"
Q   = "extend_prev_word_start"
A-q = "move_prev_long_word_start"
A-Q = "extend_prev_long_word_start"

W   = "extend_next_word_start"
A-W = "extend_next_long_word_start"
A-w = "move_next_long_word_start"

E   = "extend_next_word_end"
A-E = "extend_next_long_word_end"
A-e = "move_next_long_word_end"

[keys.insert]
"A-i" = "normal_mode"     # Maps Alt-X to enter normal mode
"C-s" = ":write" # Maps Ctrl-s to save
j = { k = "normal_mode" }
# S-; = {w = ":write"} 

[keys.select]
b   = "no_op"
B   = "no_op"
q   = "extend_prev_word_start"

A-q = "extend_prev_long_word_start"
A-w = "extend_next_long_word_start"
A-e = "extend_next_long_word_end"
