[[language]]
name = "astro"
scope = "source.astro"
file-types = ["astro"]
auto-format = true
language-server = { command = "astro-ls", args = ["--stdio"]}
config = {typescript = {tsdk = "~/.node/install/global/node_modules/typescript/lib"}, environment = "node"}