# https://frog.ski/blog/writing-your-first-kakrc
# Plugins
source "%val{config}/bundle/kak-ansi/rc/ansi.kak"
evaluate-commands %sh{ kak-tree-sitter -dks --init "$kak_session" -vvv }
# enable LSP
eval %sh{ kak-lsp --kakoune -s $kak_session}
lsp-enable

hook global KakEnd .* lsp-exit


map global user t ':enter-user-mode tree-sitter<ret>' -docstring 'tree-sitter'

colorscheme carbonfox 
colorscheme rose_pine

set-option global tabstop 2
set-option global indentwidth 2
set-option global scrolloff 1,3
set-option global ui_options ncurses_status_on_top=true
set-option global ui_options terminal_assistant=none

source "%val{config}/bundle/fzf.kak/rc/fzf.kak"
source "%val{config}/bundle/fzf.kak/rc/modules/fzf-buffer.kak"
source "%val{config}/bundle/fzf.kak/rc/modules/fzf-cd.kak"
source "%val{config}/bundle/fzf.kak/rc/modules/fzf-file.kak"
source "%val{config}/bundle/fzf.kak/rc/modules/fzf-grep.kak"
source "%val{config}/bundle/fzf.kak/rc/modules/fzf-recent.kak"
source "%val{config}/bundle/fzf.kak/rc/modules/fzf-search.kak"
evaluate-commands %sh{kak-popup init }
define-command -params 1.. picker-files %{
  popup --title "files" --kak-script %{edit %opt{popup_output}} -- %sh{ fd --type f | ~/.cargo/target/debug/harpoon }
}



enable-auto-pairs
set-option global auto_pairs ( ) { } [ ] '"' '"' "'" "'" ` ` “ ” ‘ ’ « » ‹ › 

# Highlight trailing whitespace
# add-highlighter global/ regex \h+$ 0:Error
add-highlighter global/ wrap -word -indent
add-highlighter global/ show-matching
add-highlighter global/ number-lines -hlcursor -relative -separator "  " -min-digits 3

# exit edit mode with `jk`
hook global InsertChar k %{ try %{
  exec -draft hH <a-k>jk<ret> d
  exec -with-hooks <esc>
}}

define-command acme-exec -override -params 0 %{
  evaluate-commands -draft -save-regs '|"' %sh{
    if [[ "${#kak_selection}" -eq 1 ]]
		then
			# we don't have any selected text, select anything after `$ ` and execute it, outputting it
			# below the line
	 		printf '%s\n' \
	 		"
			try %{
				execute-keys x 1s \\$<space>(.+)\n<ret>
				set-register '|' %val{selection}
				execute-keys o <esc> !<ret>
				execute-keys j d
			} catch %{
			}
			"
		else
			printf '%s\n' \
			"
			set-register '|' %val{selection}
			execute-keys o <esc> !<ret>
			execute-keys j d
			"
		fi
  }
}

map global normal z  acme-exec
map global normal <C-s> ':write<ret>'
map global normal <C-q> ':delete-buffer<ret>'
map global normal <C-g> ':acme-exec<ret>'
map global normal <ret> '<A-o>'
map global normal <S-ret> '<A-O>'
map global normal <A-o> '<A-o>'
# map global normal <ret> '<A-O>'

# Change color in insert mode
hook global InsertIdle .* %{
  # set-face window PrimaryCursor default,default+u
  # set-face window PrimaryCursorEol default,default+u
  # set-face window SecondaryCursor default,default+u
  # set-face window SecondaryCursorEol default,default+u
  # set-face window LineNumberCursor default,default+u
  # set-face window PrimarySelection default,default+u
  # set-face window SecondarySelection default,default+u
}

## set cursor to default
hook global NormalIdle .* %{
  # set-face window PrimaryCursor default,default+r
  # set-face window PrimaryCursorEol default,default+r
  # set-face window SecondaryCursor default,default+r
  # set-face window SecondaryCursorEol default,default+r
  # set-face window LineNumberCursor default,default+r
  # set-face window PrimarySelection default,default+r
  # set-face window SecondarySelection default,default+r
}

hook global ModeChange ".*:normal" %{
    face window PrimaryCursor black,white+F
    face window PrimaryCursorEol black,blue+F
    face window SecondaryCursor black,bright-green+F
    face window SecondarySelection black,green+F
}
hook global ModeChange ".*:insert" %{
    face window PrimaryCursor black,red+F
    face window PrimaryCursorEol black,red+F
    face window SecondaryCursor black,red+F
    face window SecondarySelection black,green+F
}


# tabs for autocomplete
hook global InsertCompletionShow .* %{
  try %{
    # this command temporarily removes cursors preceded by whitespace;
    # if there are no cursors left, it raises an error, does not
    # continue to execute the mapping commands, and the error is eaten
    # by the `try` command so no warning appears.
    execute-keys -draft 'h<a-K>\h<ret>'
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
    hook -once -always window InsertCompletionHide .* %{
      unmap window insert <tab> <c-n>
      unmap window insert <s-tab> <c-p>
    }
  }
}


# swap q and b
map global normal <q> "b"
map global normal <Q> "B"
map global normal <a-q> "<a-b>"
map global normal <a-Q> "<a-B>"
map global normal <b> "q"
map global normal <B> "Q"
map global normal <a-b> "<a-q>"
map global normal <a-B> "<a-Q>"

map global user k '' -docstring 'show docs for item under cursor'
map global normal <esc> ";,"
map global normal <c-v> ":comment-line<ret>"

## map -docstring "enter-user-mode" global normal <space> ":enter-user-mode<space>user<ret>"
map global user g ":bn<ret>"                        -docstring "buffer next"
map global user G ":bp<ret>"                        -docstring "buffer previous"
map global goto n <esc>:buffer-next<ret>         -docstring "buffer next"
map global goto p <esc>:buffer-previous<ret>     -docstring "buffer previous"
map global goto d <esc>:lsp-definition<ret>      -docstring "lsp definition"
map global goto D <esc>:lsp-declaration<ret>     -docstring "lsp declaration"
map global goto i <esc>:lsp-implementation<ret>  -docstring "lsp implementation"
map global goto y <esc>:lsp-type-definition<ret> -docstring "lsp type definition"
map global goto r <esc>:lsp-references<ret>      -docstring "*lsp references"

# Clipboard management mappings
map global user y "<a-|>wl-copy<ret>"               -docstring "yank to system clipboard"
map global user p "<a-!>wl-paste<ret>"              -docstring "paste from system clipboard"
map global user s ":write<ret>"                     -docstring "save current buffer"


#
# Helix Leader-mode
map global user f ':fzf-mode<ret>f'                 -docstring 'open file picker'
map global user F ':fzf-mode<ret>F'                 -docstring 'open file picker at cwd'

# No direct fzf equivalent for "explorer". Leave unmapped or bind to a file manager.
# map global user e ...  # open file explorer at workspace root
# map global user E ...  # open file explorer at buffer's directory

map global user b ':fzf-mode<ret>b'           -docstring 'open buffer picker'

# j - jumplist picker: Kakoune has jump-forward/back but no interactive jumplist picker
# map global user j ...  # open jumplist picker — NO EQUIVALENT (no interactive jumplist in kak or fzf.kak)

map global user s ':lsp-goto-document-symbol<ret>' -docstring 'open symbol picker (LSP document symbols)'
#map global user S ':lsp-workspace-symbol ""<ret>' -docstring 'open workspace symbol picker (LSP)'

map global user d ':lsp-diagnostics<ret>'     -docstring '*open diagnostic picker'
map global user g ':fzf-mode<ret>v'           -docstring 'changed file picker (fzf-vcs)'
map global user a ':lsp-code-actions<ret>'    -docstring 'perform code action'
map global user / ':fzf-mode<ret>g'           -docstring 'global search in workspace (fzf grep)'

# G - debug: no DAP in stock kak-lsp; skip unless you have kak-dap
# map global user G ...  # debug (experimental) — NO EQUIVALENT without kak-dap

# w - window management: Kakoune uses its own client/window model; no submenu equivalent
# map global user w ...  # window submenu — NO DIRECT EQUIVALENT (use tmux/splits directly)

map global user R '|xclip -selection clipboard -o<ret>'   -docstring 'replace selections with clipboard'

map global user l ':fzf-mode<ret>/'           -docstring 'local search in buffer (fzf buffer lines)'

# L - fuzzy local search in buffer: fzf-mode `/` already does this
map global user L ':fzf-mode<ret>/'           -docstring 'fuzzy local search in buffer'

map global user k ':lsp-hover<ret>'           -docstring 'show docs for item under cursor'
map global user r ':lsp-rename-prompt<ret>'   -docstring 'rename symbol'
map global user h ':lsp-highlight-references<ret>' -docstring 'select/highlight symbol references'

map global user c ':comment-line<ret>'        -docstring 'comment/uncomment selections (line)'
map global user C ':comment-block<ret>'       -docstring 'block comment/uncomment selections'

# A-c - line comment toggle: same as `c` above; bind the chord in user mode
map global user <C-c> ':comment-line<ret>'    -docstring 'line comment/uncomment selections'

# B - git blame: requires kak-git or similar
map global user B ':git blame<ret>'           -docstring 'show blame for current line (requires git.kak)'



#
# Kak LSP
# Docs: https://github.com/kakoune-lsp/kak-lsp
# 
map global user   -docstring 'LSP mode' l %{:enter-user-mode lsp<ret>}

map global insert -docstring 'Select next snippet placeholder' <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>'
map global object -docstring 'LSP any symbol' a '<a-semicolon>lsp-object<ret>'
map global object -docstring 'LSP any symbol' <a-a> '<a-semicolon>lsp-object<ret>'
map global object -docstring 'LSP function or method' f '<a-semicolon>lsp-object Function Method<ret>'
map global object -docstring 'LSP class interface or struct' t '<a-semicolon>lsp-object Class Interface Struct<ret>'
map global object -docstring 'LSP errors and warnings' d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>'
map global object -docstring 'LSP errors' D '<a-semicolon>lsp-diagnostic-object<ret>'


# #
# # FZF Mode
# #
# map global normal <c-p> ':fzf-mode<ret>'
# map global user f ':fzf-mode<ret>F' -docstring 'search for file and open it'


hook -group lsp-filetype-html global BufSetOption filetype=html %{
    set-option buffer lsp_servers %{
        # Documented options see
        # https://github.com/sublimelsp/LSP-html/blob/master/LSP-html.sublime-settings
        [vscode-html-language-server]
        root_globs = ["package.json", ".git", ".hg"]
        args = ["--stdio"]
        settings_section = "_"
        [vscode-html-language-server.settings._]
        provideFormatter = true
        [vscode-html-language-server.settings]
        embeddedLanguages.css = true
        embeddedLanguages.javascript = true
        html.autoClosingTags = true
        html.format.enable = true
        html.mirrorCursorOnMatchingTag = true
        html.validate.scripts = true
        html.validate.styles = true
        css.validate = true
        css.format.enable = true
        css.validProperties = []
        javascript.format.enable = true
        javascript.validate.enable = true
        # This is mainly a linter for HTML and to be used together with vscode-html-language-server
        # https://github.com/kristoff-it/superhtml
        # [superhtml]
        # root_globs = ["package.json", ".git", ".hg"]
        # args = ["lsp"]
        [emmet-language-server]
        args = ["--stdio"]
    }
}

hook -group lsp-language-id global BufSetOption filetype=solidity %{
  set-option buffer lsp_servers %{
    [nomicfoundation-solidity-language-server]
    args = ["--stdio"]
    root_globs = ["Foundry.toml", ".sol", ",git"]
  }
  set-option buffer lsp_language_id nomicfoundation-solidity-language-server
}
# hook -group lsp-language-id global BufCreate .*[.]sol %{
#     hook -group lsp-language-id buffer BufSetOption filetype=solidity %{
#       set-option buffer lsp_language_id nomicfoundation-solidity-language-server
#     }
# }

hook -group lsp-filetype-markdown global BufSetOption filetype=markdown %{
     set-option buffer lsp_servers %{
         [zk]
         root_globs = [".zk"]
         args = ["lsp"]
     }
}

hook -group lsp-language-id global BufSetOption filetype=sh %{
    set-option buffer lsp_language_id shellscript
}


remove-hooks global lsp-filetype-python
hook -group lsp-filetype-python global BufSetOption filetype=python %{
    set-option buffer lsp_servers %{
        [basedpyright]
        command = "basedpyright-langserver"
        root_globs = ["pyproject.toml", "setup.py", "poetry.lock", ".git", ".hg"]
        args = ["--stdio"]
        [ty]
        command = "ty"
        args = ["server"]
        root_globs = ["pyproject.toml", "setup.py", "poetry.lock", ".git", ".hg"]
        [ruff]
        args = ["server", "--quiet"]
        root_globs = ["pyproject.toml", "setup.py", "poetry.lock", ".git", ".hg"]
        settings_section = "_"
        [ruff.settings._.globalSettings]
        organizeImports = true
        fixAll = true
    }
}
map global normal -docstring 'select range' <a-i> ':lsp-selection-range<ret>'

hook global WinSetOption filetype=odin %{
    set-option buffer formatcmd "odinfmt %val{buffile}"
    set-option buffer makecmd "odin build ."
}


declare-option str scheme_repl_in "/tmp/scheme-repl-in"
declare-option str scheme_repl_out "/tmp/scheme-repl-out"


define-command scheme-repl-start -override %{
  nop %sh{
    mkfifo "$kak_opt_scheme_repl_in" 2>/dev/null
    mkfifo "$kak_opt_scheme_repl_out" 2>/dev/null
    ( exec 3<> "$kak_opt_scheme_repl_in"
      mit-scheme <&3 > "$kak_opt_scheme_repl_out" 2>&1
    ) > /dev/null 2>&1 < /dev/null &
    disown 2>/dev/null
  }
  evaluate-commands -try-client %opt{toolsclient} %{
    edit! -fifo %opt{scheme_repl_out} -scroll *scheme-repl*
  }
}

define-command scheme-send -override %{
  nop %sh{
    printf '%s\n' "$kak_selection" >> "$kak_opt_scheme_repl_in"
  }
}

map global normal <c-a> ': scheme-send<ret>' -docstring 'send selection/sexp to scheme REPL'

