modmap: 
  - name: WM
    remap: 
      CapsLock: 
        held: LeftCtrl
        alone: Esc
        alone_timeout_millis: 300
      # a+j:
      #   alone: a
      #   held: LeftMeta
      #   alone_timeout_millis: 800
      # s:
      #   alone: s
      #   held: LeftAlt
      #   alone_timeout_millis: 800
      # d:
      #   alone: d
      #   held: LeftShift
      #   alone_timeout_millis: 800
      # f:
      #   alone: f
      #   held: LeftCtrl
      #   alone_timeout_millis: 800
      # semicolon:
      #   alone: semicolon
      #   held: LeftMeta
      #   alone_timeout_millis: 800
      # l:
      #   alone: l
      #   held: LeftAlt
      #   alone_timeout_millis: 800
      # k:
      #   alone: k
      #   held: LeftShift
      #   alone_timeout_millis: 800
      # j:
      #   alone: j
      #   held: LeftCtrl
      #   alone_timeout_millis: 800
         
keymap: 
  - name: default
    remap:
      super-x:
        remap:
          b: [launch: ["firefox"]]
          e: [launch: ["nemo"]]
          c: [launch: ["code"]]
          t: [launch: ["foot"]]
          z: [launch: ["Zed"]]
          h: [launch: ["helix"]]
          
  
  - name: Default Mode
    remap:
      super-s: {set_mode: resize}
    mode: default

  - name: Resize Mode
    remap: 
      super-s: {set_mode: default}
      esc: {set_mode: default}
      enter: {set_mode: default}
      #left: {} #shrink current window
    mode: resize
